# Permalinks
permalink:      /:categories/:title

# Setup
title:          antikapital
paginate:       5
baseurl:        ""
url:            "https://antikapital.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Julio César Ibañez Rangel
  url:          http://antikapital.com
  email:        antikapital@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/antikapital/antikapital.github.io

# Gems
gems:
  - jekyll-paginate
